### ISSUE TITLE
Overescaped titles and text

### ISSUE THREAD

**Issue by TomazErjavec** [nljubesi/wikitalk-extractor#1]
topic/title is often like `title="&lt;a href=&quot;Samomor&quot;&gt;Samomor&lt;/a&gt;?"`
and text has `&amp;mdash;` and other SGML refs.

**Comment by nljubesi** [comment]
It seems that these are two separate issues (given that I understand the first one, but not the second one ;-) ).
1.  Regarding the `title` issue, what do you propose as a solution? The title is a link. I see three options:
   - leave it as is (I do not consider this a problem)
   - remove title and other annotation (information loss?)
   - move title from attribute to element
2. What does `&amp;mdash` stand for? What do you propose to do here?

You likes git? ;-) Me does.

**Comment by TomazErjavec** [comment]
1. I'd go for 3rd option, move it to element. Then you can retain the link and everything is ok, happiness and contentment reign.
2. `&amp;mdash;` is most likely overescaped `&mdash;` - but maybe this is too dangerous to try and fix.
3. I likes, maybe even loves.

**Comment by nljubesi** [comment]
1. Went with 3rd. Extract under way. Will push if no complications arise. No complications. Pushed.
2. This is noise from the original data, so should not be solved through this tool.
3. Bolan AGAIN. Bolan!
